version: "3.4"
networks:
  net:
    driver: overlay
    attachable: true

services:
  www:
    image: strapi/strapi:3.6.5
    volumes:
      - ./app:/srv/app
    depends_on:
      - mariadb
    networks:
      - net